### ISSUE TITLE
[231028] BOJ - 키 순서

### ISSUE THREAD

**Issue by dayoungee** [ConquerAlgorithm/Algorithm_Conquer#10]
1. 사이트 : BOJ
2. 제목 : 키 순서
3. 링크 : [문제링크](https://www.acmicpc.net/problem/2458)

**Comment by yoseph0310** [comment]
이 문제까지 풀고 week3 브랜치 생성해서 문제 풀이 진행해주세요 !

**Comment by dayoungee** [comment]
예엡 ~
