### ISSUE TITLE
[231104]  BOJ - 공통 부분 문자열

### ISSUE THREAD

**Issue by dayoungee** [ConquerAlgorithm/Algorithm_Conquer#18]
1. 사이트 : BOJ
2. 제목 : 공통 부분 문자열
3. 링크 : [문제링크](https://www.acmicpc.net/problem/5582)

**Comment by dayoungee** [comment]
야 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 이 문제를 풀고 시험봤어야 했네 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by yoseph0310** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ DP 응용까지 할수 있었겠다 ㅋㅋㅋㅋ
