### ISSUE TITLE
[231020] CodeTree / 왕실의 기사 대결

### ISSUE THREAD

**Issue by yoseph0310** [ConquerAlgorithm/Algorithm_Conquer#3]
1. 사이트 : CodeTree
2. 제목 : 왕실의 기사 대결
3. 링크 : [문제링크](https://www.codetree.ai/training-field/frequent-problems/problems/royal-knight-duel/description?page=1&pageSize=20)

앞으론 안까먹고 문제 꼬박 내겠습니다... ㅠ

**Comment by dayoungee** [comment]
와후 내가 4시간 날린 문제 ,,

**Comment by yoseph0310** [comment]
> 와후 내가 4시간 날린 문제 ,,

진짜 빡세긴했다 .. ㅋㅋㅋㅋ
