### ISSUE TITLE
[231021] BOJ / 공유기 설치

### ISSUE THREAD

**Issue by dayoungee** [ConquerAlgorithm/Algorithm_Conquer#4]
1. 사이트 : BOJ
2. 제목 : 공유기 설치
3. 링크 : [문제링크](https://www.acmicpc.net/problem/2110)

**Comment by yoseph0310** [comment]
@dayoungee 공유기 설치 디렉토리 Baekjoon 으로 생성해서 옮겨주세요!

**Comment by dayoungee** [comment]
아맞당 오킹
