### ISSUE TITLE
[231023] CodeTree / 루돌프의 반란

### ISSUE THREAD

**Issue by yoseph0310** [ConquerAlgorithm/Algorithm_Conquer#5]
1. 사이트 : CodeTree
2. 제목 : 루돌프의 반란
3. 링크 : [문제링크](https://www.codetree.ai/training-field/frequent-problems/problems/rudolph-rebellion/description?page=1&pageSize=20)

**Comment by yoseph0310** [comment]
진짜 4시간 꽉해서 풀었다 ㅋㅋㅋㅋㅋㅋ 와 역대급이네 난이도

**Comment by yoseph0310** [comment]
너무 지저분하게 풀었다 나... ㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by dayoungee** [comment]
> 너무 지저분하게 풀었다 나... ㅋㅋㅋㅋㅋㅋㅋㅋ

내 코드보면 놀랄 걸
