### ISSUE TITLE
[231027] Programmers / 외벽 점검

### ISSUE THREAD

**Issue by yoseph0310** [ConquerAlgorithm/Algorithm_Conquer#9]
1. 사이트 : Programmers
2. 제목 : 외벽 점검
3. 링크 : [문제링크](https://school.programmers.co.kr/learn/courses/30/lessons/60062)

**Comment by dayoungee** [comment]
내가 이거 분명 엊그제 풀다 킵해놨는데 코드가 어디갔지...

**Comment by yoseph0310** [comment]
> 내가 이거 분명 엊그제 풀다 킵해놨는데 코드가 어디갔지...

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 다시풀라는 신의계시..

**Comment by dayoungee** [comment]
anwser = 0 못 보고 두 시간 날림;
